[package]
name = "pizzeria"
version = "0.1.0"
authors = ["kotoko <kotoko@users.noreply.github.com>"]

[dependencies]
postgres = { version = "0.15.1", features = ["with-chrono"] }
postgres_array = "0.9.0"
chrono = "0.4.0"
